### ISSUE TITLE
M2 - 2.3.4.4 Class Diagram

### ISSUE THREAD

**Issue by mechproz** [mechproz/INF2001_P11-5#30]
Task title ID: 2.3.4.4 Class Diagram
Task: To create a Class Diagram that shows the relations between different entities in the project system.
Goals: To create a class diagram that accurately represents the planned system.
Success or completion criteria: To create a Class Diagram that includes the functions that IT Admins, Airline Pilots and Managers use.
Allocated time: 12 day
Start date: 11 Oct
End date: 23 Oct
Owner: James
Priority: High

**Comment by mechproz** [comment]
i. Created Class Diagram Using Week 5 Slides as a reference. BCE was kept in mind when creating entities checked with sequence diagrams to make entities consistent. The diagram has been completed but may need to be changed should any information come about after consultation with professor on 24/10/23. 
ii. The work has been committed to the repo.
iii. The work done follows the success criteria of creating a Class Diagram that includes the functions that IT Admins, Airline Pilots, and Managers use.
iv. The start date is 16 Oct and the work is completed by 16 Oct.

**Comment by DarshanKumar-SIT** [comment]
After consultation, no need to change, professor has mentioned how there is no need to include database entity in class diagram.
