### ISSUE TITLE
M2 - 2.4 Presentation Materials

### ISSUE THREAD

**Issue by LeeWeiChen2200810** [mechproz/INF2001_P11-5#34]
Task title: 2.4 Presentation Materials
Task: To Create presentation materials that will be used in the presentation to the professor for the end of M2.
Goals: Create presentation slides, notes, and recordings for the presentation.
Success or completion criteria: Successfully created presentation slides, notes, and recordings.
Allocated time: 14 days
Start date: 10 Oct
End date: 23 Oct
Owner: James
Other Members allocated to task: All Members
Priority: High

**Comment by mechproz** [comment]
i.   Successfully created presentation slides, notes, and recordings.
ii. The work has been committed to the repo
iii. The work done follows the success criteria of having created presentation slides, notes, and recordings for the presentation.
iv. The start date is 10 Oct and the work is completed by 23 Oct
