### ISSUE TITLE
M2 - 2.2.1 Schedule Zoom Consultation Meeting

### ISSUE THREAD

**Issue by mechproz** [mechproz/INF2001_P11-5#52]
Task title ID: 2.2.1 Schedule Zoom Consultation Meeting.
Task: Arrange a meeting with professor Indriyati Atmosukarto to confirm details on Class Diagram, Sequence Diagram and Component Diagram.
Goals: To add the part to complete the M2 report.
Success or completion criteria: Meeting has been scheduled with professor Indriyati Atmosukarto.
Allocated time: 1 day
Start date: 16 Oct
End date: 16 Oct
Owner: James
Priority: Medium

**Comment by DarshanKumar-SIT** [comment]
i. Successfully scheduled a meeting with Professor Indriyati Atmosukarto for the 24 Oct.
ii. The work has been committed to the repo.
iii. The work done follows the success criteria of having arranged a meeting with Professor Indriyati Atmosukarto.
iv. The start date is 16 Oct and the work is completed by 16 Oct.
