### ISSUE TITLE
M3 - 3.2.4 Project Prototype & Wireframes

### ISSUE THREAD

**Issue by JunHianL** [mechproz/INF2001_P11-5#55]
Issue/Task Details
﻿﻿﻿Task title ID: 3.2.4 Project Prototype & Wireframes.
Task: Create the prototype figma.
Goals: Create the prototype figma for M3.
﻿﻿﻿Success or completion criteria: Successful creation of prototype figma and adding it to the report.
﻿﻿﻿Allocated time: 24 days
﻿﻿﻿Start date: 29 Oct
End date: 21 Nov
Owner: Jun Hian, Darshan, WeiChen, Declan, James
Priority: High

**Comment by DarshanKumar-SIT** [comment]
i.	The figma and report section has been completed without any delays.
ii.	The work has been committed to the repo.
iii.	The work done follows the success criteria of having a completed figma for the prototype and the report writing.
iv.	The start date is 29 Oct and the work is completed by 21 Nov.
