### ISSUE TITLE
What has been done well?

### ISSUE THREAD

**Issue by JunHianL** [mechproz/INF2001_P11-5#59]
1) Major improvements to report writing such as report is now in 3rd person without "we" in it, figure labels have been added accordingly etc.
2) Requirements writing have been improved.

**Comment by mechproz** [comment]
1. Team has done well with communication and ensuring each member can complete their assigned work

**Comment by DeclanFong** [comment]
Communication is still good.  Report writing has improved quite a lot in terms of report language and labelling.

**Comment by DarshanKumar-SIT** [comment]
Improved team dynamics have been realized through strong communication, supported by consistent online and offline meetings. This strategy has created a cooperative atmosphere where every team member has equally contributed and thrived in their respective roles.

**Comment by LeeWeiChen2200810** [comment]
Software Requirements:
1. Weekly group meetings were held, and we consulted with various prof  to get their feedback. The overall quality of the requirement writing has improved significantly.

Software Design:
1. The representation of simple messages using a line with a filled-in arrowhead is correct.
2. The use of a dotted line with an empty arrowhead for return messages is accurate.
