### ISSUE TITLE
What can be done better?

### ISSUE THREAD

**Issue by JunHianL** [mechproz/INF2001_P11-5#60]
Report writing:
1) For report writing we should've added labels for all tables
2) Should have a reference section even if nothing is referenced
3) Sub headers should not be indented

Class Diagram:
1) Should have an interface class
2) Class diagram should have been aligned more properly with the component diagram
3) Proper use of stereotype

**Comment by DeclanFong** [comment]
Report writing can be more consistent. Including a reference section would have been good and sub headers should not be indented. Tables could also be labelled. 
Inheritance was not used correctly in class diagram and interfaces were not used.

**Comment by DarshanKumar-SIT** [comment]
The consistency of report writing can be enhanced. Adding a reference section would be beneficial, and subheaders should not have indents. Additionally, labeling tables would improve the report's clarity and organization.

**Comment by LeeWeiChen2200810** [comment]
Software Requirements:
1. The class diagram needs to be reviewed to ensure that the symbols used are correct and that the diagram aligns with the component diagram.
2. The concept of inheritance in the class diagram needs to be revisited to ensure that the correct stereotype is used.
3. The location of the <<interface>> classes in the class diagram needs to be clarified.

Software Design:
1. The distinction between return messages and functions needs to be clarified.
2. The nature of the "getschedule" message needs to be determined as either a message or a return message.
3. The abstraction of components is good, but it needs to be ensured that all components have the necessary interfaces to obtain the required information. For example, the ManageJobsController component needs a clear source for managing jobs.
