### ISSUE TITLE
What will we continue to improve on?

### ISSUE THREAD

**Issue by JunHianL** [mechproz/INF2001_P11-5#61]
1) Improve on report writing and making things more consistent such as adding table labels

**Comment by mechproz** [comment]
1. Team can improve on by elaborating for certain diagrams e.g. instead of just explaining why a certain method was used, can compare with other similar methods and say why those werent chosen

**Comment by DeclanFong** [comment]
Requirements and report writing was much better but can still improve. Class diagram can also be done better.

**Comment by DarshanKumar-SIT** [comment]
The report needs to be better in two main ways. First, by following the right layout and giving clearer, more detailed information about certain parts. This means making sure the report looks right and is easy to read, and also explaining things in it more fully so readers can understand everything better.

**Comment by LeeWeiChen2200810** [comment]
Software Requirements:
1. Writing clear and concise requirements
2. Aligning class diagrams with component diagrams
3. Ensuring accurate use of stereotypes in class diagrams
4. Clarifying the location of interface classes in class diagrams

Software Design:
1. Maintaining accurate distinction between return messages and functions
2. Enhancing clarity regarding the nature of the "getschedule" message
3. Validating the completeness of interfaces for components to access required information

Report Writing:
1. Ensuring consistent use of Table <> <> for generated tables
2. Including a reference list in the report
3. Maintaining proper formatting of subheaders
