### ISSUE TITLE
What has been done well?

### ISSUE THREAD

**Issue by JunHianL** [mechproz/INF2001_P11-5#62]
High and effective communication between team memebers

**Comment by mechproz** [comment]
Good communication within team, meetings were regularly held and team performed well during customer interviewer

**Comment by DeclanFong** [comment]
Communication withing the team was good and had regular meetings. We were also very well prepared for the customer meeting. Also for the follow up email, we made sure to compile all the questions we still had.

**Comment by DarshanKumar-SIT** [comment]
Enhanced team dynamics have been achieved through effective communication, facilitated by regular online and offline meetings. This approach has fostered a collaborative environment where each member has contributed equally and excelled in their assigned roles.

**Comment by LeeWeiChen2200810** [comment]
Effective communication and constructive feedback was given to each of us doing group meetings. The overall structure of the document is good and the requirements are easy to understand.The use case diagram is generally well-designed, and the size estimation is reasonable and Gantt chart is easy to follow.
