### ISSUE TITLE
What can be done better?

### ISSUE THREAD

**Issue by JunHianL** [mechproz/INF2001_P11-5#63]
Proper clarifications on uncertain stuff instead of assuming things as we went

**Comment by mechproz** [comment]
we could have clarified a few more things with the professor regarding diagram drawing and report requierments

**Comment by DeclanFong** [comment]
We could have consulted more with the professor about the diagrams and the report. Overall, the report could have been done a lot better.

**Comment by DarshanKumar-SIT** [comment]
Consulting more with the professor regarding the report could have improved the overall quality of the project. There was significant room for enhancement in the report's execution.

**Comment by LeeWeiChen2200810** [comment]
We should have consulted the lab professor on a weekly basis so that we can improve on our functional and non-functional requirements,  and improve on our use case descriptions as time pass.
