### ISSUE TITLE
What will we continue to improve on?

### ISSUE THREAD

**Issue by JunHianL** [mechproz/INF2001_P11-5#64]
1) Improve on report writing and making things more consistent
2) Improve our requirements writing
3) Improve on our use case diagram
4) Improve our gantt chart
5) Improve our documentation on the kanban board and assigning people to the respective issues

**Comment by mechproz** [comment]
1. we can improve on ensuring diagrams and tables are labelled

**Comment by DeclanFong** [comment]
We can improve on labelling the diagrams and doing higher-quality diagrams. Each report section can be improved a lot more in terms of quality and consistency, especially in report writing language. The kanban board can also be updated more regularly.

**Comment by DarshanKumar-SIT** [comment]
Enhancements can be achieved by refining the clarity and detail of the diagrams. Focusing on elevating the quality and uniformity of each report section, especially in the clarity and precision of the writing style, is crucial. Moreover, frequent and consistent updates to the project management tools, such as the Kanban board, would greatly benefit the overall workflow.

**Comment by LeeWeiChen2200810** [comment]
1. Writing clear and concise requirements
2. Designing use cases that accurately represent the system
3. Providing accurate and comprehensive estimations
4. Writing reports that are clear, concise, and professional
